const items = [
    {
        id: '001',
        image: 'images/img1.avif',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },  
    {
        id: '002',
        image: 'images/img2.avif',
        company: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        original_price: 2599,
        current_price: 1507,
        discount_percentage: 42,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/img3.avif',
        company: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        original_price: 1599,
        current_price: 495,
        discount_percentage: 69,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/img4.avif',
        company: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/img5.avif',
        company: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/img6.avif',
        company: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: 'images/img7.avif',
        company: 'The Indian Garage Co',
        item_name: 'Men Slim Fit Regular Shorts',
        original_price: 1599,
        current_price: 639,
        item_tax: "Inclusive of all taxes",
        discount_percentage: 60,
        rating: {
            stars: 3.4,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/img8.avif',
        company: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        original_price: 285,
        current_price: 142,
        discount_percentage: 50,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 2.7,
            count: 3451,
        },
    },
    {
        id: '009',
        image: 'images/pant1.avif',
        company: 'LV Ski',
        item_name: 'Technical Cotton Jogpants',
        original_price: "129,000",
        current_price: "129,000",
        discount_percentage: 0,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 6.8,
            count: 8600,
        },
    },
    {
        id: '0010',
        image: 'images/pant2.avif',
        company: 'LV',
        item_name: 'Hybrid Technical Cotton Jogpants',
        original_price: "116,000",
        current_price: "254,000",
        discount_percentage: 42,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 3.4,
            count: 2405,
        },
    },
    {
        id: '0011',
        image: 'images/pant3.avif',
        company: 'Flight Mode',
        item_name: 'Monogram Cloud Baggy Pajama Pants',
        original_price: "203,000",
        current_price: "254,000",
        discount_percentage: 25,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 9.5,
            count: "11,625",
        },
    },
    {
        id: '0012',
        image: 'images/pant4.avif',
        company: 'LV',
        item_name: 'Satin Waistband Tailored Pants',
        original_price: "164,000",
        current_price: "398,000",
        discount_percentage: 48,
        return_period: 14,
        item_tax: "Inclusive of all taxes",
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 7.5,
            count: "8,625",
        },
    }
];